project:
  type: website

website:
  title: "cykimsovanna.github.io"
  sidebar: 
    contents: 
      - href: index.qmd
        text: Home
      - href: experiences.qmd
        text: Experiences
      - section: Research & Projects
        contents:
          - text: B.S. Economics - UT Dallas
            href: UT_Dallas_BSE.qmd
          - text: M.S. Social Data Analytics & Research - UT Dallas
            href: UT_Dallas_MSSDAR.qmd
          - text: Post-Graduate Program in Data Science & Business Analytics - UT Austin
            href: UT_Austin_PGDSBA.qmd            

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual
