---
title: "Knowledge Mining Assignment 1"
format: html
---

01/28/2025

### Reviewing Breiman's *Statistical Modeling: The Two Cultures* and Shmueli's *To Explain or to Predict?*

Leo Breiman's article talks about the two cultures, namely data (stochastic) models and algorithmic (machine learning) models, while Galit Shmueli's focuses on explanatory and predictive modeling. The two articles follow very similar arguments in that mainstream academia relies too heavily on data models and/or explanatory modeling, which put more emphasis on inference of data. The problem is that people often use such method for prediction as well, which leads to many wrong conclusions. Both authors want to highlight the importance of algorithmic models and/or predictive modeling as they are crucial for making conclusions about the foreseeable future.

The main difference between the two is that Breiman strongly advocates for algorithmic models over the traditional data models because he thinks that the latter only leads to irrelevant theory and poor predictive accuracy, whereas Schmueli wants to emphasize the distinction between explanatory and predictive modeling as they serve two different purposes. She does not necessarily believe explanatory modeling is inferior to the other one—it is simply that while it is good in testing hypothesis and understanding causal relationships about past events, it is not useful when trying to generalize future events.

### Brainstorming Ideas for the Project

**1. Will AI affect future employment rates?**

-   Data collection: I can look at FRED databases, as well as other research papers that have dealt with this topic.
-   Methods: I can use a regression analysis or time series analysis.
-   Starting data project: I will first look up the data, and then regress and plot them to predict the trend of whether or not AI will increase unemployment rates in certain sectors of industry.

**2. Will tariffs affect stock market performance?**

-   Data collection: Similarly to the first hypothesis, I can look at various datasets that have been published that pertain to the various financial and economic statistics related to the stock market and tariffs.
-   Methods: I can also use regression analysis as well as time series analysis for this.
-   Starting data project: I will do the same thing as the first one.
