---
title: "Methods of Data Collection & Production Assignment 1"
format: html
---

09/09/2025

### Designing My Website

This website is built with Quarto in RStudio and published through GitHub Pages. It serves as a personal archive and portfolio for my assignments and research projects that I have done throughout my academic journey. As shown in the navigation sidebar, there are tabs that organize content by program of my studies, as well as my background and experiences. The theme used in this website is "flatly" because it looks clean and simple. I also have a separate `styles.css` file that customizes the appearances of some pages in the website. Because of the many different courses and programs that I have taken, it is not feasible to add every single assignment in the `_quarto.yml` page; besides, it would look too clustered in the navigation bar even if the system allowed me to do so. Instead, I have created dedicated overview pages for each program, where I link to relevant assignments and projects to make the website cleaner.

### Reviewing the Podcast ‘The Next Industrial Revolution Is Industrial AI’ by Barbara Humpton & Olympia Brikis

In this podcast of DataFramed, two executives from Siemens USA explain how industrial AI is starting to reshape the manufacturing industry in a positive way in terms of increased productivity and efficiency. Industrial AI could be used for predictive maintenance and quality control, such as helping analyze sensor and camera data to predict machine failures in real time. It could also help with simulations for tests and designs, as evidenced by Siemens's digital twins system used to simulate Mars rover landings with NASA. Additionally, industrial AI could take on the role of assistants for engineers and such, which could be particularly helpful to those who work in night-shifts. 

The interviewees discuss a lot about the positives that industrial AI could bring to the economy, but they fail to address any potential downside, especially when it comes to the labor force. There is no discussion about how entry-level jobs might vanish or how companies would try to cut costs by replacing human workers with AI systems. They also do not address cybersecurity risks at all, like potential hacking or ransomware attacks. I think these issues are way too critical to be looked over and as a general rule of thumb, nothing ever comes without a cost.